// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShipTracker.Api.Data;

#nullable disable

namespace ShipTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903033608_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShipTracker.Api.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CourseOverGround")
                        .HasColumnType("double precision")
                        .HasColumnName("course_over_ground");

                    b.Property<string>("Destination")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("destination");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_utc");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Mmsi")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mmsi");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<double?>("SpeedOverGround")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_over_ground");

                    b.HasKey("Id")
                        .HasName("pk_ships");

                    b.HasIndex("LastUpdatedUtc")
                        .HasDatabaseName("ix_ships_last_updated_utc");

                    b.HasIndex("Mmsi")
                        .IsUnique()
                        .HasDatabaseName("ix_ships_mmsi");

                    b.ToTable("ships", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
